openapi: 3.0.0
info:
  title: GitHub API
  version: 1.0.0
  description: Common GitHub operations focusing on repository management

paths:
  /orgs/{owner}/repos:
    get:
      summary: Get all repositories for an org
      operationId: getRepositories
      parameters:
        - name: owner
          in: path
          schema:
            type: string
            default: "CloudCore-Labs"
      responses:
        "200":
          description: Repositories retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Repository"

  /user/repos:
    post:
      summary: Create a new repository
      operationId: createRepository
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  description: Repository name
                private:
                  type: boolean
                  default: false
                description:
                  type: string
                auto_init:
                  type: boolean
                  default: false
      responses:
        "201":
          description: Repository created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Repository"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /repos/{owner}/{repo}:
    get:
      summary: Get repository information
      operationId: getRepository
      parameters:
        - name: owner
          in: path
          schema:
            type: string
            default: "CloudCore-Labs"
        - name: repo
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Repository details retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Repository"
        "404":
          description: Repository not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /repos/{owner}/{repo}/readme:
    get:
      summary: Get repository README
      operationId: getRepositoryReadme
      parameters:
        - name: owner
          in: path
          schema:
            type: string
            default: "CloudCore-Labs"
        - name: repo
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The readme for the repository
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Content"
        "404":
          description: Repository not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /repos/{owner}/{repo}/contents/{path}:
    get:
      summary: Get repository content
      operationId: getContent
      parameters:
        - name: owner
          in: path
          schema:
            type: string
            default: "CloudCore-Labs"
        - name: repo
          in: path
          required: true
          schema:
            type: string
        - name: path
          in: path
          required: true
          schema:
            type: string
        - name: ref
          in: query
          required: false
          schema:
            type: string
            description: The name of the commit/branch/tag
      responses:
        "200":
          description: Content retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Content"

    put:
      summary: Create or update file contents
      operationId: createOrUpdateFile
      parameters:
        - name: owner
          in: path
          schema:
            type: string
            default: "CloudCore-Labs"
        - name: repo
          in: path
          required: true
          schema:
            type: string
        - name: path
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [message, content]
              properties:
                message:
                  type: string
                  description: Commit message
                content:
                  type: string
                  description: Base64 encoded content
                branch:
                  type: string
                  description: Branch name
                sha:
                  type: string
                  description: SHA of the file being replaced
      responses:
        "200":
          description: File updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Content"
        "201":
          description: File created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Content"

  /repos/{owner}/{repo}/branches:
    get:
      summary: List branches
      operationId: listBranches
      parameters:
        - name: owner
          in: path
          schema:
            type: string
            default: "CloudCore-Labs"
        - name: repo
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Branches retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Branch"

  /repos/{owner}/{repo}/issues:
    get:
      summary: List repository issues
      operationId: listRepositoryIssues
      parameters:
        - name: owner
          in: path
          schema:
            type: string
          default: "CloudCore-Labs"
        - name: repo
          in: path
          required: true
          schema:
            type: string
        - name: state
          in: query
          schema:
            type: string
            enum: [open, closed, all]
            default: open
        - name: sort
          in: query
          schema:
            type: string
            enum: [created, updated, comments]
            default: created
        - name: direction
          in: query
          schema:
            type: string
            enum: [asc, desc]
            default: desc
        - name: per_page
          in: query
          schema:
            type: integer
            default: 30
        - name: page
          in: query
          schema:
            type: integer
            default: 1
      responses:
        "200":
          description: Issues retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Issue"

    post:
      summary: Create an issue
      operationId: createIssue
      parameters:
        - name: owner
          in: path
          schema:
            type: string
            default: "CloudCore-Labs"
        - name: repo
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
              properties:
                title:
                  type: string
                body:
                  type: string
                assignees:
                  type: array
                  items:
                    type: string
                labels:
                  type: array
                  items:
                    type: string
      responses:
        "201":
          description: Issue created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Issue"

  /repos/{owner}/{repo}/issues/{issue_number}:
    get:
      summary: Get a single issue
      operationId: getIssue
      parameters:
        - name: owner
          in: path
          schema:
            type: string
            default: "CloudCore-Labs"
        - name: repo
          in: path
          required: true
          schema:
            type: string
        - name: issue_number
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Issue retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Issue"

    patch:
      summary: Update an issue
      operationId: updateIssue
      parameters:
        - name: owner
          in: path
          schema:
            type: string
            default: "CloudCore-Labs"
        - name: repo
          in: path
          required: true
          schema:
            type: string
        - name: issue_number
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
                state:
                  type: string
                  enum: [open, closed]
                assignees:
                  type: array
                  items:
                    type: string
                labels:
                  type: array
                  items:
                    type: string
      responses:
        "200":
          description: Issue updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Issue"

components:
  schemas:
    Repository:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        full_name:
          type: string
        private:
          type: boolean
        description:
          type: string
        url:
          type: string
        clone_url:
          type: string
          format: uri
        stargazers_count:
          type: integer
        open_issues_count:
          type: integer
        forks_count:
          type: integer
        default_branch:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        pushed_at:
          type: string
          format: date-time

    Content:
      type: object
      properties:
        type:
          type: string
          enum: [file, dir]
        size:
          type: integer
        name:
          type: string
        path:
          type: string
        content:
          type: string
        sha:
          type: string
        url:
          type: string
          format: uri

    Branch:
      type: object
      properties:
        name:
          type: string
        commit:
          type: object
          properties:
            sha:
              type: string
            url:
              type: string
              format: uri

    Issue:
      type: object
      properties:
        id:
          type: integer
          format: int64
        number:
          type: integer
        title:
          type: string
        body:
          type: string
        state:
          type: string
          enum: [open, closed]
        user:
          type: object
          properties:
            login:
              type: string
            id:
              type: integer
              format: int64
        labels:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
              color:
                type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        closed_at:
          type: string
          format: date-time
          nullable: true
        assignees:
          type: array
          items:
            type: object
            properties:
              login:
                type: string
              id:
                type: integer

    Error:
      type: object
      properties:
        message:
          type: string
        documentation_url:
          type: string
