openapi: 3.0.0
info:
  title: Slack API
  description: Common Slack operations focusing on messaging and reactions
  version: 1.0.0
  contact:
    name: Slack API Support
    url: https://api.slack.com/

servers:
  - url: https://slack.com/api
    description: Slack Web API

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Message:
      type: object
      properties:
        text:
          type: string
        blocks:
          type: array
          items:
            $ref: '#/components/schemas/Block'
        thread_ts:
          type: string
          description: Timestamp of the parent message to reply to
        reply_broadcast:
          type: boolean
          description: Used in conjunction with thread_ts to broadcast a thread reply
        unfurl_links:
          type: boolean
        unfurl_media:
          type: boolean
        parse:
          type: string
          enum: [none, full]
        mrkdwn:
          type: boolean
          default: true

    Block:
      type: object
      properties:
        type:
          type: string
          enum: [section, divider, header, image, actions, context]
        text:
          type: object
          properties:
            type:
              type: string
              enum: [plain_text, mrkdwn]
            text:
              type: string
        fields:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              text:
                type: string
        accessory:
          type: object
          description: Block accessory like button or select menu

    User:
      type: object
      properties:
        id:
          type: string
        team_id:
          type: string
        name:
          type: string
        real_name:
          type: string
        email:
          type: string
        presence:
          type: string
          enum: [active, away]
        is_bot:
          type: boolean
        is_admin:
          type: boolean
        is_owner:
          type: boolean
        is_restricted:
          type: boolean

    Channel:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        is_channel:
          type: boolean
        is_group:
          type: boolean
        is_im:
          type: boolean
        is_private:
          type: boolean
        created:
          type: integer
        creator:
          type: string
        members:
          type: array
          items:
            type: string
        topic:
          type: object
          properties:
            value:
              type: string
            creator:
              type: string
            last_set:
              type: integer
        purpose:
          type: object
          properties:
            value:
              type: string
            creator:
              type: string
            last_set:
              type: integer

    File:
      type: object
      properties:
        id:
          type: string
        created:
          type: integer
        timestamp:
          type: integer
        name:
          type: string
        title:
          type: string
        mimetype:
          type: string
        filetype:
          type: string
        pretty_type:
          type: string
        user:
          type: string
        size:
          type: integer
        mode:
          type: string
        is_public:
          type: boolean
        url_private:
          type: string
        url_private_download:
          type: string
        thumb_64:
          type: string
        thumb_80:
          type: string
        thumb_360:
          type: string
        thumb_360_gif:
          type: string
        permalink:
          type: string
        permalink_public:
          type: string
        channels:
          type: array
          items:
            type: string

    SearchResult:
      type: object
      properties:
        matches:
          type: array
          items:
            type: object
            properties:
              channel:
                type: string
              ts:
                type: string
              message:
                $ref: '#/components/schemas/Message'
        total:
          type: integer
        pagination:
          type: object
          properties:
            page:
              type: integer
            per_page:
              type: integer
            total:
              type: integer
            page_count:
              type: integer

    ThreadInfo:
      type: object
      properties:
        thread_ts:
          type: string
        total_replies:
          type: integer
        reply_users_count:
          type: integer
        reply_users:
          type: array
          items:
            type: string
        last_reply:
          type: string
        unread_replies:
          type: integer

    Emoji:
      type: object
      properties:
        name:
          type: string
        url:
          type: string
        created:
          type: integer
        team_id:
          type: string
        user_id:
          type: string
        is_alias:
          type: boolean
        alias_for:
          type: string
        available:
          type: boolean

paths:
  /chat.postMessage:
    post:
      summary: Send a message to a channel
      operationId: postMessage
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - channel
                - text
              properties:
                channel:
                  type: string
                  description: Channel, private group, or DM channel ID
                text:
                  type: string
                blocks:
                  type: array
                  items:
                    $ref: '#/components/schemas/Block'
                thread_ts:
                  type: string
                reply_broadcast:
                  type: boolean
                unfurl_links:
                  type: boolean
                unfurl_media:
                  type: boolean
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  channel:
                    type: string
                  ts:
                    type: string
                  message:
                    $ref: '#/components/schemas/Message'

  /files.upload:
    post:
      summary: Upload a file
      operationId: uploadFile
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: string
                  format: binary
                filename:
                  type: string
                initial_comment:
                  type: string
                channels:
                  type: string
                  description: Comma-separated list of channel IDs
                thread_ts:
                  type: string
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  file:
                    $ref: '#/components/schemas/File'

  /reactions.add:
    post:
      summary: Add a reaction (emoji) to a message
      operationId: addReaction
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - channel
                - name
                - timestamp
              properties:
                channel:
                  type: string
                name:
                  type: string
                  description: Reaction (emoji) name without colons
                timestamp:
                  type: string
                  description: Message timestamp to add reaction to
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean

  /reactions.remove:
    post:
      summary: Remove a reaction (emoji) from a message
      operationId: removeReaction
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - channel
                - name
                - timestamp
              properties:
                channel:
                  type: string
                name:
                  type: string
                  description: Reaction (emoji) name without colons
                timestamp:
                  type: string
                  description: Message timestamp to remove reaction from
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean

  /emoji.list:
    get:
      summary: List custom emoji for a team
      operationId: listEmoji
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Success response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  emoji:
                    type: object
                    additionalProperties:
                      type: string
                      description: URL to emoji image or alias to another emoji
